name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: How would you catagorize this issue?
      multiple: true
      options:
        - Hardware Compatibility
        - BLE
        - Serial
        - Other
    validations:
      required: true

  - type: dropdown
    id: hardware
    attributes:
      label: Hardware
      description: This repository supports MuziWorks Superbase only.
      multiple: true
      options:
        - MuziWorks Superbase (muzi-base)
    validations:
      required: true

  - type: checkboxes
    id: mui
    attributes:
      label: Is this bug report about any UI (https://meshtastic.org/docs/configuration/device-uis/) component firmware?
      options:
        - label: BaseUI

  - type: input
    id: version
    attributes:
      label: Firmware Version
      description: This can be found on the device's screen or via one of the apps.
      placeholder: x.x.x.yyyyyyy
    validations:
      required: true

  - type: textarea
    id: body
    attributes:
      label: Description
      description: Please provide details on what steps you performed for this to happen.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If you have any log output to help in diagnosing your bug, please provide it here.
      render: Shell
    validations:
      required: false
